### ISSUE TITLE
Breadcrumb links don't work

### ISSUE THREAD

**Issue by srmagura** [markerikson/react-community-tools-practices-cheatsheet#23]
I noticed the breadcrumbs links do not work. E.g. go to https://react-community-tools-practices-cheatsheet.netlify.app/styling/plain-css and try to click the "Styling" breadcrumb. It does nothing.

This example shows how to fix it by adding a `link` key to a `type: category` sidebar item: https://docusaurus.io/docs/sidebar#complex-sidebars-example  

Do you want me to convert `sidebars.js` to the non-shorthand syntax so we can make the breadcrumbs work properly? Or should we just disable breadcrumbs? Or leave the links non-functional?

Funny, I noticed that the breadcrumb links do not work in the official Redux docs either. E.g. try to click "Introduction" on [this page](https://redux.js.org/introduction/installation).

**Comment by markerikson** [comment]
yeah, for the Redux docs at least, there is no single page associated with "Introduction" - it's a category.

tbh I'm not worried about the breadcrumbs stuff for now.  I _do_ think we should figure out what the right overall site name and page branding should be, and fix the header to be more useful.

**Comment by srmagura** [comment]
I had an idea on this... I think the simplest fix is to make a PR to Docusaurus that removes the hover and `cursor: pointer` styles from the breadcrumb links if there's not actually an `href`. Will add that to my todo list...

I will keep this open though, since it would be nice if the "Styling" breadcrumb actually linked to "Styling: Overview". Though I agree it's a very low priority issue.

**Comment by srmagura** [comment]
https://github.com/facebookincubator/infima/pull/266
