### ISSUE TITLE
How About React-Router?

### ISSUE THREAD

**Issue by ryota-murakami** [markerikson/react-community-tools-practices-cheatsheet#26]
This is one of essential library in the React Community traditionally.  
But recently React-Router betting data-fetch optimization like this [Ryan Florence](https://ryanflorence.com/) talk.

[When To Fetch: Remixing React Router - Ryan Florence](https://youtu.be/95B8mnhzoCM)

This movement relating the who handle 'Framework' category in the here i think.

**Comment by markerikson** [comment]
Routing is probably worth talking about at some point, but I'm less concerned about that for now - I don't see too many people asking "What router should I choose?" :)

**Comment by ryota-murakami** [comment]
Absolutely, Thank you for the answer!
